// Hardcoded major-update names for game-version compatibility tagging.
// Sourced from https://about.openwf.io/versions (major update names only,
// not individual build/patch numbers — those are too granular to be a
// useful compatibility tag). Best-effort list pulled via an AI-summarized
// fetch of that page, not a raw scrape — review against the live page
// before treating it as exhaustive/exact.
//
// "all" is a sentinel, not a real update name: a mod tagged with it is
// claimed compatible with every version, and is mutually exclusive with
// picking specific versions (see Upload.tsx).

export const ALL_VERSIONS_TAG = "all";

export const GAME_VERSIONS: string[] = [
  "The Shadowgrapher",
  "Vauban Heirloom",
  "The Old Peace",
  "The Vallis Undermind",
  "Caliban Prime",
  "Isleweaver",
  "Yareli Prime",
  "Techrot Encore",
  "1999",
  "Koumei & the Five Fates",
  "The Lotus Eaters",
  "Jade Shadows",
  "Dante Unbound",
  "Whispers in the Walls",
  "Abyss of Dagath",
  "Echoes of Duviri",
  "The Seven Crimes of Kullervo",
  "The Duviri Paradox",
  "Citrine's Last Wish",
  "Lua's Prey",
  "Veilbreaker",
  "Echoes of the Zariman",
  "Angels of the Zariman",
  "The New War",
  "Sisters of Parvos",
  "Call of the Tempestarii",
  "Orphix Venom",
  "Echoes of Deimos",
  "Heart of Deimos",
  "Derelict Shift",
  "The Deadlock Protocol",
  "Empyrean",
  "Rising Tide",
  "The Old Blood",
  "Saint of Altra",
  "The Jovian Concord",
  "Buried Debts",
  "Fortuna",
  "Chimera",
  "Mask of the Revenant",
  "The Sacrifice",
  "Beasts of the Sanctuary",
  "Plains of Eidolon",
  "Chains of Harrow",
  "Octavia's Anthem",
  "The Glast Gambit",
  "The War Within",
  "The Silver Grove",
  "Sands of Inaros",
  "The Second Dream",
  "The Jordas Precept",
  "Echoes of the Sentient",
  "Tubemen of Regor",
  "Sanctuary",
  "Eyes of Blight",
  "Mesa Update",
  "Archwing",
  "The Mad Cephalon",
  "The Dark Sectors",
  "Zephyr Rises",
  "Shadows Of The Dead",
  "Vor's Revenge",
  "Rise of the Warlords",
  "Stormbringer",
];
