-- Seed data for local scale testing: 50 modders + 50 mods (+ 1 version each).
-- All ids are prefixed "seedtest-" for easy identification/cleanup.
-- Generated by generate-seed.mjs; see cleanup-test-data.sql to remove.

BEGIN TRANSACTION;

INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-01', 'Alex (Test 01)', 'seedtest_alex01', NULL, NULL, 0, 0, datetime('now', '-90 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-02', 'Jamie (Test 02)', 'seedtest_jamie02', NULL, NULL, 0, 0, datetime('now', '-89 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-03', 'Sam (Test 03)', 'seedtest_sam03', NULL, NULL, 0, 0, datetime('now', '-87 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-04', 'Riley (Test 04)', 'seedtest_riley04', NULL, NULL, 0, 0, datetime('now', '-85 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-05', 'Kai (Test 05)', 'seedtest_kai05', NULL, NULL, 0, 0, datetime('now', '-83 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-06', 'Morgan (Test 06)', 'seedtest_morgan06', NULL, NULL, 0, 0, datetime('now', '-81 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-07', 'Casey (Test 07)', 'seedtest_casey07', NULL, NULL, 0, 0, datetime('now', '-80 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-08', 'Drew (Test 08)', 'seedtest_drew08', NULL, NULL, 0, 0, datetime('now', '-78 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-09', 'Skyler (Test 09)', 'seedtest_skyler09', NULL, NULL, 0, 0, datetime('now', '-76 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-10', 'Robin (Test 10)', 'seedtest_robin10', NULL, NULL, 0, 0, datetime('now', '-74 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-11', 'Quinn (Test 11)', 'seedtest_quinn11', NULL, NULL, 0, 0, datetime('now', '-72 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-12', 'Avery (Test 12)', 'seedtest_avery12', NULL, NULL, 0, 0, datetime('now', '-71 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-13', 'Reese (Test 13)', 'seedtest_reese13', NULL, NULL, 0, 0, datetime('now', '-69 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-14', 'Rowan (Test 14)', 'seedtest_rowan14', NULL, NULL, 0, 0, datetime('now', '-67 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-15', 'Sage (Test 15)', 'seedtest_sage15', NULL, NULL, 0, 0, datetime('now', '-65 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-16', 'Jordan (Test 16)', 'seedtest_jordan16', NULL, NULL, 0, 0, datetime('now', '-63 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-17', 'Taylor (Test 17)', 'seedtest_taylor17', NULL, NULL, 0, 0, datetime('now', '-62 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-18', 'Emerson (Test 18)', 'seedtest_emerson18', NULL, NULL, 0, 0, datetime('now', '-60 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-19', 'Finley (Test 19)', 'seedtest_finley19', NULL, NULL, 0, 0, datetime('now', '-58 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-20', 'Hayden (Test 20)', 'seedtest_hayden20', NULL, NULL, 0, 0, datetime('now', '-56 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-21', 'Blake (Test 21)', 'seedtest_blake21', NULL, NULL, 0, 0, datetime('now', '-54 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-22', 'Cameron (Test 22)', 'seedtest_cameron22', NULL, NULL, 0, 0, datetime('now', '-53 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-23', 'Dakota (Test 23)', 'seedtest_dakota23', NULL, NULL, 0, 0, datetime('now', '-51 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-24', 'Elliot (Test 24)', 'seedtest_elliot24', NULL, NULL, 0, 0, datetime('now', '-49 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-25', 'Frankie (Test 25)', 'seedtest_frankie25', NULL, NULL, 0, 0, datetime('now', '-47 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-26', 'Gray (Test 26)', 'seedtest_gray26', NULL, NULL, 0, 0, datetime('now', '-45 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-27', 'Harper (Test 27)', 'seedtest_harper27', NULL, NULL, 0, 0, datetime('now', '-44 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-28', 'Indigo (Test 28)', 'seedtest_indigo28', NULL, NULL, 0, 0, datetime('now', '-42 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-29', 'Jules (Test 29)', 'seedtest_jules29', NULL, NULL, 0, 0, datetime('now', '-40 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-30', 'Kendall (Test 30)', 'seedtest_kendall30', NULL, NULL, 0, 0, datetime('now', '-38 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-31', 'Lane (Test 31)', 'seedtest_lane31', NULL, NULL, 0, 0, datetime('now', '-36 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-32', 'Marlowe (Test 32)', 'seedtest_marlowe32', NULL, NULL, 0, 0, datetime('now', '-35 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-33', 'Nico (Test 33)', 'seedtest_nico33', NULL, NULL, 0, 0, datetime('now', '-33 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-34', 'Oakley (Test 34)', 'seedtest_oakley34', NULL, NULL, 0, 0, datetime('now', '-31 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-35', 'Parker (Test 35)', 'seedtest_parker35', NULL, NULL, 0, 0, datetime('now', '-29 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-36', 'Quincy (Test 36)', 'seedtest_quincy36', NULL, NULL, 0, 0, datetime('now', '-28 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-37', 'Remy (Test 37)', 'seedtest_remy37', NULL, NULL, 0, 0, datetime('now', '-26 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-38', 'Shiloh (Test 38)', 'seedtest_shiloh38', NULL, NULL, 0, 0, datetime('now', '-24 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-39', 'Tatum (Test 39)', 'seedtest_tatum39', NULL, NULL, 0, 0, datetime('now', '-22 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-40', 'Val (Test 40)', 'seedtest_val40', NULL, NULL, 0, 0, datetime('now', '-20 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-41', 'Winter (Test 41)', 'seedtest_winter41', NULL, NULL, 0, 0, datetime('now', '-18 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-42', 'Zion (Test 42)', 'seedtest_zion42', NULL, NULL, 0, 0, datetime('now', '-17 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-43', 'Ash (Test 43)', 'seedtest_ash43', NULL, NULL, 0, 0, datetime('now', '-15 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-44', 'Bex (Test 44)', 'seedtest_bex44', NULL, NULL, 0, 0, datetime('now', '-13 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-45', 'Cricket (Test 45)', 'seedtest_cricket45', NULL, NULL, 0, 0, datetime('now', '-11 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-46', 'Dune (Test 46)', 'seedtest_dune46', NULL, NULL, 0, 0, datetime('now', '-9 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-47', 'Echo (Test 47)', 'seedtest_echo47', NULL, NULL, 0, 0, datetime('now', '-8 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-48', 'Fox (Test 48)', 'seedtest_fox48', NULL, NULL, 0, 0, datetime('now', '-6 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-49', 'Gale (Test 49)', 'seedtest_gale49', NULL, NULL, 0, 0, datetime('now', '-4 days'));
INSERT INTO modders (id, name, username, api_key_hash, password_hash, is_admin, is_banned, created_at)
VALUES ('seedtest-acct-50', 'Haze (Test 50)', 'seedtest_haze50', NULL, NULL, 0, 0, datetime('now', '-2 days'));

INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-01', 'Frost Sound Pack', 'Alex (Test 01)', 'A sample metadata patch for scale testing — frost sound pack variant #01.', 'metadata-patch', NULL, '50% 50%', '[]', '["cosmetic","warframe"]', 0, 'seedtest-acct-01', datetime('now', '-90 days'), datetime('now', '-90 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-01', '1.0.0', 'seedtest-mod-01.zip', 'https://example.invalid/seedtest/seedtest-mod-01.zip', -1, 1024, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-90 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-02', 'Ember Glyph Bundle', 'Jamie (Test 02)', 'A sample pluto script for scale testing — ember glyph bundle variant #02.', 'pluto-script', NULL, '50% 50%', '[]', '["qol","weapon"]', 37, 'seedtest-acct-02', datetime('now', '-89 days'), datetime('now', '-88 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-02', '1.0.0', 'seedtest-mod-02.zip', 'https://example.invalid/seedtest/seedtest-mod-02.zip', -2, 1037, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-89 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-03', 'Void Syandana', 'Sam (Test 03)', 'A sample other for scale testing — void syandana variant #03.', 'other', NULL, '50% 50%', '[]', '["utility","operator"]', 74, 'seedtest-acct-03', datetime('now', '-87 days'), datetime('now', '-85 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-03', '1.0.0', 'seedtest-mod-03.zip', 'https://example.invalid/seedtest/seedtest-mod-03.zip', -3, 1050, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-87 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-04', 'Nova Armor Set', 'Riley (Test 04)', 'A sample metadata patch for scale testing — nova armor set variant #04.', 'metadata-patch', NULL, '50% 50%', '[]', '["warframe","companion"]', 111, 'seedtest-acct-04', datetime('now', '-85 days'), datetime('now', '-82 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-04', '1.0.0', 'seedtest-mod-04.zip', 'https://example.invalid/seedtest/seedtest-mod-04.zip', -4, 1063, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-85 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-05', 'Prime Sigil Pack', 'Kai (Test 05)', 'A sample pluto script for scale testing — prime sigil pack variant #05.', 'pluto-script', NULL, '50% 50%', '[]', '["weapon","ui"]', 148, 'seedtest-acct-05', datetime('now', '-83 days'), datetime('now', '-79 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-05', '1.0.0', 'seedtest-mod-05.zip', 'https://example.invalid/seedtest/seedtest-mod-05.zip', -5, 1076, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-83 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-06', 'Shadow Auto Farm', 'Morgan (Test 06)', 'A sample other for scale testing — shadow auto farm variant #06.', 'other', NULL, '50% 50%', '[]', '["operator","audio"]', 185, 'seedtest-acct-06', datetime('now', '-81 days'), datetime('now', '-76 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-06', '1.0.0', 'seedtest-mod-06.zip', 'https://example.invalid/seedtest/seedtest-mod-06.zip', -6, 1089, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-81 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-07', 'Aurora Companion Skin', 'Casey (Test 07)', 'A sample metadata patch for scale testing — aurora companion skin variant #07.', 'metadata-patch', NULL, '50% 50%', '[]', '["companion","automation"]', 222, 'seedtest-acct-07', datetime('now', '-80 days'), datetime('now', '-74 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-07', '1.0.0', 'seedtest-mod-07.zip', 'https://example.invalid/seedtest/seedtest-mod-07.zip', -7, 1102, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-80 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-08', 'Crimson Weapon Skin', 'Drew (Test 08)', 'A sample pluto script for scale testing — crimson weapon skin variant #08.', 'pluto-script', NULL, '50% 50%', '[]', '["ui","cosmetic"]', 259, 'seedtest-acct-08', datetime('now', '-78 days'), datetime('now', '-71 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-08', '1.0.0', 'seedtest-mod-08.zip', 'https://example.invalid/seedtest/seedtest-mod-08.zip', -8, 1115, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-78 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-09', 'Glacial Warframe Recolor', 'Skyler (Test 09)', 'A sample other for scale testing — glacial warframe recolor variant #09.', 'other', NULL, '50% 50%', '[]', '["audio","qol"]', 296, 'seedtest-acct-09', datetime('now', '-76 days'), datetime('now', '-68 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-09', '1.0.0', 'seedtest-mod-09.zip', 'https://example.invalid/seedtest/seedtest-mod-09.zip', -9, 1128, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-76 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-10', 'Volt Deco Pack', 'Robin (Test 10)', 'A sample metadata patch for scale testing — volt deco pack variant #10.', 'metadata-patch', NULL, '50% 50%', '[]', '["automation","utility"]', 333, 'seedtest-acct-10', datetime('now', '-74 days'), datetime('now', '-65 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-10', '1.0.0', 'seedtest-mod-10.zip', 'https://example.invalid/seedtest/seedtest-mod-10.zip', -10, 1141, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-74 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-11', 'Radiant Emote Set', 'Quinn (Test 11)', 'A sample pluto script for scale testing — radiant emote set variant #11.', 'pluto-script', NULL, '50% 50%', '[]', '["cosmetic","warframe"]', 370, 'seedtest-acct-11', datetime('now', '-72 days'), datetime('now', '-72 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-11', '1.0.0', 'seedtest-mod-11.zip', 'https://example.invalid/seedtest/seedtest-mod-11.zip', -11, 1154, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-72 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-12', 'Obsidian Landing Craft Skin', 'Avery (Test 12)', 'A sample other for scale testing — obsidian landing craft skin variant #12.', 'other', NULL, '50% 50%', '[]', '["qol","weapon"]', 407, 'seedtest-acct-12', datetime('now', '-71 days'), datetime('now', '-70 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-12', '1.0.0', 'seedtest-mod-12.zip', 'https://example.invalid/seedtest/seedtest-mod-12.zip', -12, 1167, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-71 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-13', 'Storm Operator Accessory', 'Reese (Test 13)', 'A sample metadata patch for scale testing — storm operator accessory variant #13.', 'metadata-patch', NULL, '50% 50%', '[]', '["utility","operator"]', 444, 'seedtest-acct-13', datetime('now', '-69 days'), datetime('now', '-67 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-13', '1.0.0', 'seedtest-mod-13.zip', 'https://example.invalid/seedtest/seedtest-mod-13.zip', -13, 1180, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-69 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-14', 'Lunar Recolor', 'Rowan (Test 14)', 'A sample pluto script for scale testing — lunar recolor variant #14.', 'pluto-script', NULL, '50% 50%', '[]', '["warframe","companion"]', 481, 'seedtest-acct-14', datetime('now', '-67 days'), datetime('now', '-64 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-14', '1.0.0', 'seedtest-mod-14.zip', 'https://example.invalid/seedtest/seedtest-mod-14.zip', -14, 1193, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-67 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-15', 'Solar Overhaul', 'Sage (Test 15)', 'A sample other for scale testing — solar overhaul variant #15.', 'other', NULL, '50% 50%', '[]', '["weapon","ui"]', 18, 'seedtest-acct-15', datetime('now', '-65 days'), datetime('now', '-61 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-15', '1.0.0', 'seedtest-mod-15.zip', 'https://example.invalid/seedtest/seedtest-mod-15.zip', -15, 1206, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-65 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-16', 'Ferrous FX Pack', 'Jordan (Test 16)', 'A sample metadata patch for scale testing — ferrous fx pack variant #16.', 'metadata-patch', NULL, '50% 50%', '[]', '["operator","audio"]', 55, 'seedtest-acct-16', datetime('now', '-63 days'), datetime('now', '-58 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-16', '1.0.0', 'seedtest-mod-16.zip', 'https://example.invalid/seedtest/seedtest-mod-16.zip', -16, 1219, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-63 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-17', 'Toxic Skin Set', 'Taylor (Test 17)', 'A sample pluto script for scale testing — toxic skin set variant #17.', 'pluto-script', NULL, '50% 50%', '[]', '["companion","automation"]', 92, 'seedtest-acct-17', datetime('now', '-62 days'), datetime('now', '-56 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-17', '1.0.0', 'seedtest-mod-17.zip', 'https://example.invalid/seedtest/seedtest-mod-17.zip', -17, 1232, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-62 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-18', 'Corrupted Loot Helper', 'Emerson (Test 18)', 'A sample other for scale testing — corrupted loot helper variant #18.', 'other', NULL, '50% 50%', '[]', '["ui","cosmetic"]', 129, 'seedtest-acct-18', datetime('now', '-60 days'), datetime('now', '-53 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-18', '1.0.0', 'seedtest-mod-18.zip', 'https://example.invalid/seedtest/seedtest-mod-18.zip', -18, 1245, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-60 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-19', 'Ancient Ability Tweaks', 'Finley (Test 19)', 'A sample metadata patch for scale testing — ancient ability tweaks variant #19.', 'metadata-patch', NULL, '50% 50%', '[]', '["audio","qol"]', 166, 'seedtest-acct-19', datetime('now', '-58 days'), datetime('now', '-50 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-19', '1.0.0', 'seedtest-mod-19.zip', 'https://example.invalid/seedtest/seedtest-mod-19.zip', -19, 1258, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-58 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-20', 'Neon HUD Fix', 'Hayden (Test 20)', 'A sample pluto script for scale testing — neon hud fix variant #20.', 'pluto-script', NULL, '50% 50%', '[]', '["automation","utility"]', 203, 'seedtest-acct-20', datetime('now', '-56 days'), datetime('now', '-47 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-20', '1.0.0', 'seedtest-mod-20.zip', 'https://example.invalid/seedtest/seedtest-mod-20.zip', -20, 1271, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-56 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-21', 'Chrome Sound Pack', 'Blake (Test 21)', 'A sample other for scale testing — chrome sound pack variant #21.', 'other', NULL, '50% 50%', '[]', '["cosmetic","warframe"]', 240, 'seedtest-acct-21', datetime('now', '-54 days'), datetime('now', '-54 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-21', '1.0.0', 'seedtest-mod-21.zip', 'https://example.invalid/seedtest/seedtest-mod-21.zip', -21, 1284, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-54 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-22', 'Vengeful Glyph Bundle', 'Cameron (Test 22)', 'A sample metadata patch for scale testing — vengeful glyph bundle variant #22.', 'metadata-patch', NULL, '50% 50%', '[]', '["qol","weapon"]', 277, 'seedtest-acct-22', datetime('now', '-53 days'), datetime('now', '-52 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-22', '1.0.0', 'seedtest-mod-22.zip', 'https://example.invalid/seedtest/seedtest-mod-22.zip', -22, 1297, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-53 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-23', 'Silent Syandana', 'Dakota (Test 23)', 'A sample pluto script for scale testing — silent syandana variant #23.', 'pluto-script', NULL, '50% 50%', '[]', '["utility","operator"]', 314, 'seedtest-acct-23', datetime('now', '-51 days'), datetime('now', '-49 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-23', '1.0.0', 'seedtest-mod-23.zip', 'https://example.invalid/seedtest/seedtest-mod-23.zip', -23, 1310, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-51 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-24', 'Feral Armor Set', 'Elliot (Test 24)', 'A sample other for scale testing — feral armor set variant #24.', 'other', NULL, '50% 50%', '[]', '["warframe","companion"]', 351, 'seedtest-acct-24', datetime('now', '-49 days'), datetime('now', '-46 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-24', '1.0.0', 'seedtest-mod-24.zip', 'https://example.invalid/seedtest/seedtest-mod-24.zip', -24, 1323, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-49 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-25', 'Astral Sigil Pack', 'Frankie (Test 25)', 'A sample metadata patch for scale testing — astral sigil pack variant #25.', 'metadata-patch', NULL, '50% 50%', '[]', '["weapon","ui"]', 388, 'seedtest-acct-25', datetime('now', '-47 days'), datetime('now', '-43 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-25', '1.0.0', 'seedtest-mod-25.zip', 'https://example.invalid/seedtest/seedtest-mod-25.zip', -25, 1336, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-47 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-26', 'Frost Auto Farm', 'Gray (Test 26)', 'A sample pluto script for scale testing — frost auto farm variant #26.', 'pluto-script', NULL, '50% 50%', '[]', '["operator","audio"]', 425, 'seedtest-acct-26', datetime('now', '-45 days'), datetime('now', '-40 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-26', '1.0.0', 'seedtest-mod-26.zip', 'https://example.invalid/seedtest/seedtest-mod-26.zip', -26, 1349, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-45 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-27', 'Ember Companion Skin', 'Harper (Test 27)', 'A sample other for scale testing — ember companion skin variant #27.', 'other', NULL, '50% 50%', '[]', '["companion","automation"]', 462, 'seedtest-acct-27', datetime('now', '-44 days'), datetime('now', '-38 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-27', '1.0.0', 'seedtest-mod-27.zip', 'https://example.invalid/seedtest/seedtest-mod-27.zip', -27, 1362, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-44 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-28', 'Void Weapon Skin', 'Indigo (Test 28)', 'A sample metadata patch for scale testing — void weapon skin variant #28.', 'metadata-patch', NULL, '50% 50%', '[]', '["ui","cosmetic"]', 499, 'seedtest-acct-28', datetime('now', '-42 days'), datetime('now', '-35 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-28', '1.0.0', 'seedtest-mod-28.zip', 'https://example.invalid/seedtest/seedtest-mod-28.zip', -28, 1375, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-42 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-29', 'Nova Warframe Recolor', 'Jules (Test 29)', 'A sample pluto script for scale testing — nova warframe recolor variant #29.', 'pluto-script', NULL, '50% 50%', '[]', '["audio","qol"]', 36, 'seedtest-acct-29', datetime('now', '-40 days'), datetime('now', '-32 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-29', '1.0.0', 'seedtest-mod-29.zip', 'https://example.invalid/seedtest/seedtest-mod-29.zip', -29, 1388, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-40 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-30', 'Prime Deco Pack', 'Kendall (Test 30)', 'A sample other for scale testing — prime deco pack variant #30.', 'other', NULL, '50% 50%', '[]', '["automation","utility"]', 73, 'seedtest-acct-30', datetime('now', '-38 days'), datetime('now', '-29 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-30', '1.0.0', 'seedtest-mod-30.zip', 'https://example.invalid/seedtest/seedtest-mod-30.zip', -30, 1401, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-38 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-31', 'Shadow Emote Set', 'Lane (Test 31)', 'A sample metadata patch for scale testing — shadow emote set variant #31.', 'metadata-patch', NULL, '50% 50%', '[]', '["cosmetic","warframe"]', 110, 'seedtest-acct-31', datetime('now', '-36 days'), datetime('now', '-36 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-31', '1.0.0', 'seedtest-mod-31.zip', 'https://example.invalid/seedtest/seedtest-mod-31.zip', -31, 1414, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-36 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-32', 'Aurora Landing Craft Skin', 'Marlowe (Test 32)', 'A sample pluto script for scale testing — aurora landing craft skin variant #32.', 'pluto-script', NULL, '50% 50%', '[]', '["qol","weapon"]', 147, 'seedtest-acct-32', datetime('now', '-35 days'), datetime('now', '-34 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-32', '1.0.0', 'seedtest-mod-32.zip', 'https://example.invalid/seedtest/seedtest-mod-32.zip', -32, 1427, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-35 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-33', 'Crimson Operator Accessory', 'Nico (Test 33)', 'A sample other for scale testing — crimson operator accessory variant #33.', 'other', NULL, '50% 50%', '[]', '["utility","operator"]', 184, 'seedtest-acct-33', datetime('now', '-33 days'), datetime('now', '-31 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-33', '1.0.0', 'seedtest-mod-33.zip', 'https://example.invalid/seedtest/seedtest-mod-33.zip', -33, 1440, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-33 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-34', 'Glacial Recolor', 'Oakley (Test 34)', 'A sample metadata patch for scale testing — glacial recolor variant #34.', 'metadata-patch', NULL, '50% 50%', '[]', '["warframe","companion"]', 221, 'seedtest-acct-34', datetime('now', '-31 days'), datetime('now', '-28 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-34', '1.0.0', 'seedtest-mod-34.zip', 'https://example.invalid/seedtest/seedtest-mod-34.zip', -34, 1453, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-31 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-35', 'Volt Overhaul', 'Parker (Test 35)', 'A sample pluto script for scale testing — volt overhaul variant #35.', 'pluto-script', NULL, '50% 50%', '[]', '["weapon","ui"]', 258, 'seedtest-acct-35', datetime('now', '-29 days'), datetime('now', '-25 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-35', '1.0.0', 'seedtest-mod-35.zip', 'https://example.invalid/seedtest/seedtest-mod-35.zip', -35, 1466, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-29 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-36', 'Radiant FX Pack', 'Quincy (Test 36)', 'A sample other for scale testing — radiant fx pack variant #36.', 'other', NULL, '50% 50%', '[]', '["operator","audio"]', 295, 'seedtest-acct-36', datetime('now', '-28 days'), datetime('now', '-23 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-36', '1.0.0', 'seedtest-mod-36.zip', 'https://example.invalid/seedtest/seedtest-mod-36.zip', -36, 1479, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-28 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-37', 'Obsidian Skin Set', 'Remy (Test 37)', 'A sample metadata patch for scale testing — obsidian skin set variant #37.', 'metadata-patch', NULL, '50% 50%', '[]', '["companion","automation"]', 332, 'seedtest-acct-37', datetime('now', '-26 days'), datetime('now', '-20 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-37', '1.0.0', 'seedtest-mod-37.zip', 'https://example.invalid/seedtest/seedtest-mod-37.zip', -37, 1492, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-26 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-38', 'Storm Loot Helper', 'Shiloh (Test 38)', 'A sample pluto script for scale testing — storm loot helper variant #38.', 'pluto-script', NULL, '50% 50%', '[]', '["ui","cosmetic"]', 369, 'seedtest-acct-38', datetime('now', '-24 days'), datetime('now', '-17 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-38', '1.0.0', 'seedtest-mod-38.zip', 'https://example.invalid/seedtest/seedtest-mod-38.zip', -38, 1505, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-24 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-39', 'Lunar Ability Tweaks', 'Tatum (Test 39)', 'A sample other for scale testing — lunar ability tweaks variant #39.', 'other', NULL, '50% 50%', '[]', '["audio","qol"]', 406, 'seedtest-acct-39', datetime('now', '-22 days'), datetime('now', '-14 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-39', '1.0.0', 'seedtest-mod-39.zip', 'https://example.invalid/seedtest/seedtest-mod-39.zip', -39, 1518, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-22 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-40', 'Solar HUD Fix', 'Val (Test 40)', 'A sample metadata patch for scale testing — solar hud fix variant #40.', 'metadata-patch', NULL, '50% 50%', '[]', '["automation","utility"]', 443, 'seedtest-acct-40', datetime('now', '-20 days'), datetime('now', '-11 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-40', '1.0.0', 'seedtest-mod-40.zip', 'https://example.invalid/seedtest/seedtest-mod-40.zip', -40, 1531, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-20 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-41', 'Ferrous Sound Pack', 'Winter (Test 41)', 'A sample pluto script for scale testing — ferrous sound pack variant #41.', 'pluto-script', NULL, '50% 50%', '[]', '["cosmetic","warframe"]', 480, 'seedtest-acct-41', datetime('now', '-18 days'), datetime('now', '-18 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-41', '1.0.0', 'seedtest-mod-41.zip', 'https://example.invalid/seedtest/seedtest-mod-41.zip', -41, 1544, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-18 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-42', 'Toxic Glyph Bundle', 'Zion (Test 42)', 'A sample other for scale testing — toxic glyph bundle variant #42.', 'other', NULL, '50% 50%', '[]', '["qol","weapon"]', 17, 'seedtest-acct-42', datetime('now', '-17 days'), datetime('now', '-16 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-42', '1.0.0', 'seedtest-mod-42.zip', 'https://example.invalid/seedtest/seedtest-mod-42.zip', -42, 1557, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-17 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-43', 'Corrupted Syandana', 'Ash (Test 43)', 'A sample metadata patch for scale testing — corrupted syandana variant #43.', 'metadata-patch', NULL, '50% 50%', '[]', '["utility","operator"]', 54, 'seedtest-acct-43', datetime('now', '-15 days'), datetime('now', '-13 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-43', '1.0.0', 'seedtest-mod-43.zip', 'https://example.invalid/seedtest/seedtest-mod-43.zip', -43, 1570, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-15 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-44', 'Ancient Armor Set', 'Bex (Test 44)', 'A sample pluto script for scale testing — ancient armor set variant #44.', 'pluto-script', NULL, '50% 50%', '[]', '["warframe","companion"]', 91, 'seedtest-acct-44', datetime('now', '-13 days'), datetime('now', '-10 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-44', '1.0.0', 'seedtest-mod-44.zip', 'https://example.invalid/seedtest/seedtest-mod-44.zip', -44, 1583, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-13 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-45', 'Neon Sigil Pack', 'Cricket (Test 45)', 'A sample other for scale testing — neon sigil pack variant #45.', 'other', NULL, '50% 50%', '[]', '["weapon","ui"]', 128, 'seedtest-acct-45', datetime('now', '-11 days'), datetime('now', '-7 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-45', '1.0.0', 'seedtest-mod-45.zip', 'https://example.invalid/seedtest/seedtest-mod-45.zip', -45, 1596, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-11 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-46', 'Chrome Auto Farm', 'Dune (Test 46)', 'A sample metadata patch for scale testing — chrome auto farm variant #46.', 'metadata-patch', NULL, '50% 50%', '[]', '["operator","audio"]', 165, 'seedtest-acct-46', datetime('now', '-9 days'), datetime('now', '-4 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-46', '1.0.0', 'seedtest-mod-46.zip', 'https://example.invalid/seedtest/seedtest-mod-46.zip', -46, 1609, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-9 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-47', 'Vengeful Companion Skin', 'Echo (Test 47)', 'A sample pluto script for scale testing — vengeful companion skin variant #47.', 'pluto-script', NULL, '50% 50%', '[]', '["companion","automation"]', 202, 'seedtest-acct-47', datetime('now', '-8 days'), datetime('now', '-2 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-47', '1.0.0', 'seedtest-mod-47.zip', 'https://example.invalid/seedtest/seedtest-mod-47.zip', -47, 1622, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-8 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-48', 'Silent Weapon Skin', 'Fox (Test 48)', 'A sample other for scale testing — silent weapon skin variant #48.', 'other', NULL, '50% 50%', '[]', '["ui","cosmetic"]', 239, 'seedtest-acct-48', datetime('now', '-6 days'), datetime('now', '-0 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-48', '1.0.0', 'seedtest-mod-48.zip', 'https://example.invalid/seedtest/seedtest-mod-48.zip', -48, 1635, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-6 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-49', 'Feral Warframe Recolor', 'Gale (Test 49)', 'A sample metadata patch for scale testing — feral warframe recolor variant #49.', 'metadata-patch', NULL, '50% 50%', '[]', '["audio","qol"]', 276, 'seedtest-acct-49', datetime('now', '-4 days'), datetime('now', '-0 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-49', '1.0.0', 'seedtest-mod-49.zip', 'https://example.invalid/seedtest/seedtest-mod-49.zip', -49, 1648, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-4 days'));
INSERT INTO mods (id, name, author, description, category, thumbnail_url, thumbnail_position, screenshot_urls, tags, download_count, owner_id, created_at, updated_at)
VALUES ('seedtest-mod-50', 'Astral Deco Pack', 'Haze (Test 50)', 'A sample pluto script for scale testing — astral deco pack variant #50.', 'pluto-script', NULL, '50% 50%', '[]', '["automation","utility"]', 313, 'seedtest-acct-50', datetime('now', '-2 days'), datetime('now', '-0 days'));
INSERT INTO mod_versions (mod_id, version, file_name, download_url, github_release_id, file_size, checksum, game_versions, changelog, created_at)
VALUES ('seedtest-mod-50', '1.0.0', 'seedtest-mod-50.zip', 'https://example.invalid/seedtest/seedtest-mod-50.zip', -50, 1661, '0000000000000000000000000000000000000000000000000000000000000000', '["all"]', 'Initial seed version.', datetime('now', '-2 days'));

COMMIT;
