BEGIN TRANSACTION;

INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-01', 'seedtest-reviewer-1', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-01', 'seedtest-reviewer-2', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-01', 'seedtest-reviewer-3', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-01', 'seedtest-reviewer-4', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-01', 'seedtest-reviewer-5', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-01', 'seedtest-reviewer-6', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-01', 'seedtest-reviewer-7', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-01', 'seedtest-reviewer-8', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-02', 'seedtest-reviewer-9', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-02', 'seedtest-reviewer-10', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-02', 'seedtest-reviewer-11', 5);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-02', 'Void_Walker', 'Exactly what I was looking for.');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-02', 'Clem', 'Had an issue installing but figured it out — great mod.');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-02', 'Ordis_Fan', 'Love the recolor, looks amazing in-game.');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-04', 'seedtest-reviewer-12', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-04', 'seedtest-reviewer-13', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-04', 'seedtest-reviewer-14', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-04', 'seedtest-reviewer-15', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-04', 'seedtest-reviewer-16', 4);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-04', 'Ordis_Fan', 'Love the recolor, looks amazing in-game.');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-05', 'seedtest-reviewer-17', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-05', 'seedtest-reviewer-18', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-05', 'seedtest-reviewer-19', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-05', 'seedtest-reviewer-20', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-05', 'seedtest-reviewer-21', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-05', 'seedtest-reviewer-22', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-05', 'seedtest-reviewer-23', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-05', 'seedtest-reviewer-24', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-05', 'seedtest-reviewer-25', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-05', 'seedtest-reviewer-26', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-05', 'seedtest-reviewer-27', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-05', 'seedtest-reviewer-28', 2);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-06', 'Tenno77', 'Any plans to update this for the next patch?');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-06', 'Void_Walker', 'Exactly what I was looking for.');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-06', 'Clem', 'Had an issue installing but figured it out — great mod.');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-07', 'seedtest-reviewer-29', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-07', 'seedtest-reviewer-30', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-08', 'seedtest-reviewer-31', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-08', 'seedtest-reviewer-32', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-08', 'seedtest-reviewer-33', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-08', 'seedtest-reviewer-34', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-08', 'seedtest-reviewer-35', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-08', 'seedtest-reviewer-36', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-08', 'seedtest-reviewer-37', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-08', 'seedtest-reviewer-38', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-08', 'seedtest-reviewer-39', 2);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-08', 'Clem', 'Had an issue installing but figured it out — great mod.');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-10', 'seedtest-reviewer-40', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-10', 'seedtest-reviewer-41', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-10', 'seedtest-reviewer-42', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-10', 'seedtest-reviewer-43', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-10', 'seedtest-reviewer-44', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-10', 'seedtest-reviewer-45', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-10', 'seedtest-reviewer-46', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-10', 'seedtest-reviewer-47', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-10', 'seedtest-reviewer-48', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-10', 'seedtest-reviewer-49', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-10', 'seedtest-reviewer-50', 1);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-10', 'Nova', 'Works great, thanks for this!');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-10', 'Tenno77', 'Any plans to update this for the next patch?');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-10', 'Void_Walker', 'Exactly what I was looking for.');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-11', 'seedtest-reviewer-51', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-11', 'seedtest-reviewer-52', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-11', 'seedtest-reviewer-53', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-11', 'seedtest-reviewer-54', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-11', 'seedtest-reviewer-55', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-11', 'seedtest-reviewer-56', 2);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-12', 'Void_Walker', 'Exactly what I was looking for.');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-13', 'seedtest-reviewer-57', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-13', 'seedtest-reviewer-58', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-13', 'seedtest-reviewer-59', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-13', 'seedtest-reviewer-60', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-13', 'seedtest-reviewer-61', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-13', 'seedtest-reviewer-62', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-13', 'seedtest-reviewer-63', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-13', 'seedtest-reviewer-64', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-14', 'seedtest-reviewer-65', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-14', 'seedtest-reviewer-66', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-14', 'seedtest-reviewer-67', 2);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-14', 'Ordis_Fan', 'Love the recolor, looks amazing in-game.');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-14', 'Nova', 'Works great, thanks for this!');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-14', 'Tenno77', 'Any plans to update this for the next patch?');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-16', 'seedtest-reviewer-68', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-16', 'seedtest-reviewer-69', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-16', 'seedtest-reviewer-70', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-16', 'seedtest-reviewer-71', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-16', 'seedtest-reviewer-72', 1);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-16', 'Tenno77', 'Any plans to update this for the next patch?');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-17', 'seedtest-reviewer-73', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-17', 'seedtest-reviewer-74', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-17', 'seedtest-reviewer-75', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-17', 'seedtest-reviewer-76', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-17', 'seedtest-reviewer-77', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-17', 'seedtest-reviewer-78', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-17', 'seedtest-reviewer-79', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-17', 'seedtest-reviewer-80', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-17', 'seedtest-reviewer-81', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-17', 'seedtest-reviewer-82', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-17', 'seedtest-reviewer-83', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-17', 'seedtest-reviewer-84', 4);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-18', 'Clem', 'Had an issue installing but figured it out — great mod.');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-18', 'Ordis_Fan', 'Love the recolor, looks amazing in-game.');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-18', 'Nova', 'Works great, thanks for this!');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-19', 'seedtest-reviewer-85', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-19', 'seedtest-reviewer-86', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-20', 'seedtest-reviewer-87', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-20', 'seedtest-reviewer-88', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-20', 'seedtest-reviewer-89', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-20', 'seedtest-reviewer-90', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-20', 'seedtest-reviewer-91', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-20', 'seedtest-reviewer-92', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-20', 'seedtest-reviewer-93', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-20', 'seedtest-reviewer-94', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-20', 'seedtest-reviewer-95', 4);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-20', 'Nova', 'Works great, thanks for this!');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-22', 'seedtest-reviewer-96', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-22', 'seedtest-reviewer-97', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-22', 'seedtest-reviewer-98', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-22', 'seedtest-reviewer-99', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-22', 'seedtest-reviewer-100', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-22', 'seedtest-reviewer-101', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-22', 'seedtest-reviewer-102', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-22', 'seedtest-reviewer-103', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-22', 'seedtest-reviewer-104', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-22', 'seedtest-reviewer-105', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-22', 'seedtest-reviewer-106', 3);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-22', 'Void_Walker', 'Exactly what I was looking for.');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-22', 'Clem', 'Had an issue installing but figured it out — great mod.');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-22', 'Ordis_Fan', 'Love the recolor, looks amazing in-game.');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-23', 'seedtest-reviewer-107', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-23', 'seedtest-reviewer-108', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-23', 'seedtest-reviewer-109', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-23', 'seedtest-reviewer-110', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-23', 'seedtest-reviewer-111', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-23', 'seedtest-reviewer-112', 4);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-24', 'Ordis_Fan', 'Love the recolor, looks amazing in-game.');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-25', 'seedtest-reviewer-113', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-25', 'seedtest-reviewer-114', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-25', 'seedtest-reviewer-115', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-25', 'seedtest-reviewer-116', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-25', 'seedtest-reviewer-117', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-25', 'seedtest-reviewer-118', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-25', 'seedtest-reviewer-119', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-25', 'seedtest-reviewer-120', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-26', 'seedtest-reviewer-121', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-26', 'seedtest-reviewer-122', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-26', 'seedtest-reviewer-123', 4);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-26', 'Tenno77', 'Any plans to update this for the next patch?');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-26', 'Void_Walker', 'Exactly what I was looking for.');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-26', 'Clem', 'Had an issue installing but figured it out — great mod.');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-28', 'seedtest-reviewer-124', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-28', 'seedtest-reviewer-125', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-28', 'seedtest-reviewer-126', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-28', 'seedtest-reviewer-127', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-28', 'seedtest-reviewer-128', 3);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-28', 'Clem', 'Had an issue installing but figured it out — great mod.');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-29', 'seedtest-reviewer-129', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-29', 'seedtest-reviewer-130', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-29', 'seedtest-reviewer-131', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-29', 'seedtest-reviewer-132', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-29', 'seedtest-reviewer-133', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-29', 'seedtest-reviewer-134', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-29', 'seedtest-reviewer-135', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-29', 'seedtest-reviewer-136', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-29', 'seedtest-reviewer-137', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-29', 'seedtest-reviewer-138', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-29', 'seedtest-reviewer-139', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-29', 'seedtest-reviewer-140', 1);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-30', 'Nova', 'Works great, thanks for this!');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-30', 'Tenno77', 'Any plans to update this for the next patch?');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-30', 'Void_Walker', 'Exactly what I was looking for.');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-31', 'seedtest-reviewer-141', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-31', 'seedtest-reviewer-142', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-32', 'seedtest-reviewer-143', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-32', 'seedtest-reviewer-144', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-32', 'seedtest-reviewer-145', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-32', 'seedtest-reviewer-146', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-32', 'seedtest-reviewer-147', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-32', 'seedtest-reviewer-148', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-32', 'seedtest-reviewer-149', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-32', 'seedtest-reviewer-150', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-32', 'seedtest-reviewer-151', 1);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-32', 'Void_Walker', 'Exactly what I was looking for.');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-34', 'seedtest-reviewer-152', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-34', 'seedtest-reviewer-153', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-34', 'seedtest-reviewer-154', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-34', 'seedtest-reviewer-155', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-34', 'seedtest-reviewer-156', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-34', 'seedtest-reviewer-157', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-34', 'seedtest-reviewer-158', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-34', 'seedtest-reviewer-159', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-34', 'seedtest-reviewer-160', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-34', 'seedtest-reviewer-161', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-34', 'seedtest-reviewer-162', 5);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-34', 'Ordis_Fan', 'Love the recolor, looks amazing in-game.');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-34', 'Nova', 'Works great, thanks for this!');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-34', 'Tenno77', 'Any plans to update this for the next patch?');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-35', 'seedtest-reviewer-163', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-35', 'seedtest-reviewer-164', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-35', 'seedtest-reviewer-165', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-35', 'seedtest-reviewer-166', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-35', 'seedtest-reviewer-167', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-35', 'seedtest-reviewer-168', 1);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-36', 'Tenno77', 'Any plans to update this for the next patch?');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-37', 'seedtest-reviewer-169', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-37', 'seedtest-reviewer-170', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-37', 'seedtest-reviewer-171', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-37', 'seedtest-reviewer-172', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-37', 'seedtest-reviewer-173', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-37', 'seedtest-reviewer-174', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-37', 'seedtest-reviewer-175', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-37', 'seedtest-reviewer-176', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-38', 'seedtest-reviewer-177', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-38', 'seedtest-reviewer-178', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-38', 'seedtest-reviewer-179', 1);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-38', 'Clem', 'Had an issue installing but figured it out — great mod.');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-38', 'Ordis_Fan', 'Love the recolor, looks amazing in-game.');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-38', 'Nova', 'Works great, thanks for this!');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-40', 'seedtest-reviewer-180', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-40', 'seedtest-reviewer-181', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-40', 'seedtest-reviewer-182', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-40', 'seedtest-reviewer-183', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-40', 'seedtest-reviewer-184', 5);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-40', 'Nova', 'Works great, thanks for this!');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-41', 'seedtest-reviewer-185', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-41', 'seedtest-reviewer-186', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-41', 'seedtest-reviewer-187', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-41', 'seedtest-reviewer-188', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-41', 'seedtest-reviewer-189', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-41', 'seedtest-reviewer-190', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-41', 'seedtest-reviewer-191', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-41', 'seedtest-reviewer-192', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-41', 'seedtest-reviewer-193', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-41', 'seedtest-reviewer-194', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-41', 'seedtest-reviewer-195', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-41', 'seedtest-reviewer-196', 3);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-42', 'Void_Walker', 'Exactly what I was looking for.');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-42', 'Clem', 'Had an issue installing but figured it out — great mod.');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-42', 'Ordis_Fan', 'Love the recolor, looks amazing in-game.');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-43', 'seedtest-reviewer-197', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-43', 'seedtest-reviewer-198', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-44', 'seedtest-reviewer-199', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-44', 'seedtest-reviewer-200', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-44', 'seedtest-reviewer-201', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-44', 'seedtest-reviewer-202', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-44', 'seedtest-reviewer-203', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-44', 'seedtest-reviewer-204', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-44', 'seedtest-reviewer-205', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-44', 'seedtest-reviewer-206', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-44', 'seedtest-reviewer-207', 3);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-44', 'Ordis_Fan', 'Love the recolor, looks amazing in-game.');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-46', 'seedtest-reviewer-208', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-46', 'seedtest-reviewer-209', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-46', 'seedtest-reviewer-210', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-46', 'seedtest-reviewer-211', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-46', 'seedtest-reviewer-212', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-46', 'seedtest-reviewer-213', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-46', 'seedtest-reviewer-214', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-46', 'seedtest-reviewer-215', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-46', 'seedtest-reviewer-216', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-46', 'seedtest-reviewer-217', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-46', 'seedtest-reviewer-218', 2);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-46', 'Tenno77', 'Any plans to update this for the next patch?');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-46', 'Void_Walker', 'Exactly what I was looking for.');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-46', 'Clem', 'Had an issue installing but figured it out — great mod.');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-47', 'seedtest-reviewer-219', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-47', 'seedtest-reviewer-220', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-47', 'seedtest-reviewer-221', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-47', 'seedtest-reviewer-222', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-47', 'seedtest-reviewer-223', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-47', 'seedtest-reviewer-224', 3);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-48', 'Clem', 'Had an issue installing but figured it out — great mod.');
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-49', 'seedtest-reviewer-225', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-49', 'seedtest-reviewer-226', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-49', 'seedtest-reviewer-227', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-49', 'seedtest-reviewer-228', 3);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-49', 'seedtest-reviewer-229', 4);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-49', 'seedtest-reviewer-230', 5);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-49', 'seedtest-reviewer-231', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-49', 'seedtest-reviewer-232', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-50', 'seedtest-reviewer-233', 1);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-50', 'seedtest-reviewer-234', 2);
INSERT INTO reviews (mod_id, reviewer_id, rating) VALUES ('seedtest-mod-50', 'seedtest-reviewer-235', 3);
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-50', 'Nova', 'Works great, thanks for this!');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-50', 'Tenno77', 'Any plans to update this for the next patch?');
INSERT INTO comments (mod_id, author_name, body) VALUES ('seedtest-mod-50', 'Void_Walker', 'Exactly what I was looking for.');

COMMIT;
